export const themeStyles = {
  modernMinimalist: {
    body: 'bg-gray-50 text-gray-800 font-sans',
    header: 'bg-white shadow-sm',
    blogName: 'text-4xl text-gray-900 font-light',
    heading: 'text-gray-800 font-light',
    card: 'bg-white rounded-lg shadow-sm border border-gray-200',
    button: 'bg-gray-800 hover:bg-gray-700 text-white font-light py-2 px-4 rounded-full transition duration-300',
    input: 'border border-gray-300 rounded-full focus:outline-none focus:ring-2 focus:ring-gray-400 focus:border-transparent',
    select: 'border border-gray-300 rounded-full focus:outline-none focus:ring-2 focus:ring-gray-400 focus:border-transparent',
    category: 'text-gray-500',
    footer: 'bg-gray-100 text-gray-600',
    footerLink: 'text-gray-700 hover:text-gray-900 transition duration-300',
    navLink: 'text-gray-600 hover:text-gray-800 transition duration-300',
    label: 'text-gray-700',
    text: 'text-gray-600',
    accent: 'text-gray-800',
  },
  vibrantFoodie: {
    body: 'bg-yellow-50 text-gray-900 font-sans',
    header: 'bg-gradient-to-r from-yellow-400 via-red-500 to-pink-500',
    blogName: 'text-4xl text-white font-bold',
    heading: 'text-pink-600 font-bold',
    card: 'bg-white rounded-xl shadow-lg border-2 border-yellow-200 overflow-hidden transform transition duration-300 hover:scale-105',
    button: 'bg-gradient-to-r from-yellow-400 to-pink-500 hover:from-pink-500 hover:to-yellow-400 text-white font-bold py-2 px-4 rounded-full transition duration-300',
    input: 'border-2 border-yellow-300 rounded-full focus:outline-none focus:ring-2 focus:ring-pink-400 focus:border-transparent',
    select: 'border-2 border-yellow-300 rounded-full focus:outline-none focus:ring-2 focus:ring-pink-400 focus:border-transparent',
    category: 'text-pink-500 font-semibold',
    footer: 'bg-gradient-to-r from-yellow-400 via-red-500 to-pink-500 text-white',
    footerLink: 'text-yellow-100 hover:text-white transition duration-300',
    navLink: 'text-white hover:text-yellow-200 transition duration-300',
    label: 'text-pink-600',
    text: 'text-gray-700',
    accent: 'text-pink-600',
  },
  elegant: {
    body: 'bg-gray-50 text-gray-900 font-serif',
    header: 'bg-gray-800 text-white',
    blogName: 'text-4xl text-white font-light',
    heading: 'text-gray-800 font-light',
    card: 'bg-white border border-gray-200 rounded-lg shadow-md',
    button: 'bg-gray-800 hover:bg-gray-900 text-white font-light py-2 px-4 rounded',
    input: 'border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-400',
    select: 'border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-400',
    category: 'text-gray-600',
    footer: 'bg-gray-800 text-white',
    footerLink: 'text-gray-300 hover:text-white',
    navLink: 'text-white hover:text-gray-300',
    label: 'text-gray-700',
    text: 'text-gray-600',
    accent: 'text-gray-800',
  },
  vibrant: {
    body: 'bg-purple-50 text-purple-900 font-sans',
    header: 'bg-purple-600 text-white',
    blogName: 'text-4xl text-white font-extrabold',
    heading: 'text-purple-800 font-extrabold',
    card: 'bg-white border border-purple-200 rounded-xl shadow-lg',
    button: 'bg-purple-500 hover:bg-purple-600 text-white font-semibold py-2 px-4 rounded-full',
    input: 'border border-purple-300 rounded-full focus:outline-none focus:ring-2 focus:ring-purple-500',
    select: 'border border-purple-300 rounded-full focus:outline-none focus:ring-2 focus:ring-purple-500',
    category: 'text-purple-600',
    footer: 'bg-purple-600 text-white',
    footerLink: 'text-purple-200 hover:text-white',
    navLink: 'text-white hover:text-purple-200',
    label: 'text-purple-700',
    text: 'text-purple-600',
    accent: 'text-purple-800',
  },
  rusticCharm: {
    body: 'bg-amber-50 text-amber-900 font-serif',
    header: 'bg-amber-800 text-amber-100',
    blogName: 'text-4xl text-amber-100 font-bold',
    heading: 'text-amber-800 font-bold',
    card: 'bg-white border-2 border-amber-200 rounded-lg shadow-md',
    button: 'bg-amber-700 hover:bg-amber-800 text-amber-100 font-semibold py-2 px-4 rounded',
    input: 'border-2 border-amber-300 rounded focus:outline-none focus:ring-2 focus:ring-amber-500',
    select: 'border-2 border-amber-300 rounded focus:outline-none focus:ring-2 focus:ring-amber-500',
    category: 'text-amber-600 font-semibold',
    footer: 'bg-amber-800 text-amber-100',
    footerLink: 'text-amber-200 hover:text-white',
    navLink: 'text-amber-100 hover:text-white',
    label: 'text-amber-700',
    text: 'text-amber-800',
    accent: 'text-amber-700',
  },
  modernGourmet: {
    body: 'bg-slate-50 text-slate-800 font-sans',
    header: 'bg-slate-900 text-white',
    blogName: 'text-4xl text-white font-extrabold',
    heading: 'text-slate-800 font-bold',
    card: 'bg-white rounded-xl shadow-lg border border-slate-200 overflow-hidden',
    button: 'bg-slate-800 hover:bg-slate-700 text-white font-semibold py-2 px-4 rounded-md transition duration-300',
    input: 'border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-slate-500 focus:border-transparent',
    select: 'border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-slate-500 focus:border-transparent',
    category: 'text-slate-600 font-medium',
    footer: 'bg-slate-900 text-white',
    footerLink: 'text-slate-300 hover:text-white transition duration-300',
    navLink: 'text-white hover:text-slate-300 transition duration-300',
    label: 'text-slate-700',
    text: 'text-slate-600',
    accent: 'text-slate-800',
  },
};

export type ThemeKey = keyof typeof themeStyles;